module CodegenTests

open System
open System.IO
open System.Threading.Tasks
open Xunit
open MigLib
open MigLib.Codegen

let private await (t: Task<'a>) = t.GetAwaiter().GetResult()

let private withTempDir (action: string -> unit) =
  let dir = Path.Combine(Path.GetTempPath(), $"mig-cg-{Guid.NewGuid():N}")
  Directory.CreateDirectory dir |> ignore

  try
    action dir
  finally
    try
      Directory.Delete(dir, true)
    with _ ->
      ()

[<Fact>]
let ``generate emits one file per relation`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001_users.sql"),
      """
-- mig:rel User
-- mig:ops insert, insert_many, select_by_id, select_one_by(email), upsert, upsert_many, delete_by_id
-- mig:bool active
-- mig:datetime created_at
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  active INTEGER NOT NULL,
  created_at TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok result ->
      Assert.Equal(1, result.relationCount)
      Assert.Single result.generatedFiles |> ignore
      let userPath = Path.Combine(output, "User.fs")
      Assert.True(File.Exists userPath)
      let source = File.ReadAllText userPath
      Assert.Contains("// <auto-generated />", source)
      Assert.Contains("module TestApp.Data.Stores.User", source)
      Assert.Contains("type User =", source)
      Assert.Contains("type UserInsert =", source)
      Assert.Contains("let insert ", source)
      Assert.Contains("let insertMany ", source)
      Assert.Contains("let selectById ", source)
      Assert.Contains("let selectOneByEmail ", source)
      Assert.Contains("let upsert ", source)
      Assert.Contains("let upsertMany ", source)
      Assert.Contains("let deleteById ", source)
      Assert.Contains("bool", source)
      Assert.Contains("DateTimeOffset", source))

[<Fact>]
let ``generate emits select_by_or_insert`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops select_by_or_insert(username), select_by_id
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "AppUser.fs"))
      Assert.Contains("let selectByUsernameOrInsert (row: AppUserInsert) : TxnStep<AppUser> =", source)
      Assert.Contains("type AppUserInsert =", source)
      Assert.Contains("INSERT INTO [app_user]", source)
      Assert.Contains("WHERE [username] = @username LIMIT 1", source)
      Assert.Contains("select_by_or_insert failed to load inserted row", source))

[<Fact>]
let ``generate refuses select_by_or_insert on views`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL
) STRICT;

-- mig:ops select_by_or_insert(username)
CREATE VIEW active_user AS SELECT id, username FROM app_user;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Ok _ -> Assert.Fail "expected write op on view to fail"
    | Error e -> Assert.Contains("write op not allowed on view", e))

[<Fact>]
let ``generate emits select_top and select_bottom`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops select_top(created_at, 200), select_bottom(created_at, 10)
CREATE TABLE event_log (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL,
  body TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "EventLog.fs"))
      Assert.Contains("let selectTopCreatedAt200 : TxnStep<EventLog list> =", source)
      Assert.Contains("ORDER BY [created_at] DESC LIMIT 200", source)
      Assert.Contains("let selectBottomCreatedAt10 : TxnStep<EventLog list> =", source)
      Assert.Contains("ORDER BY [created_at] ASC LIMIT 10", source))

[<Fact>]
let ``generate emits select_range`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops select_range(created_at desc, id)
CREATE TABLE event_log (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL,
  body TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "EventLog.fs"))

      Assert.Contains(
        "let selectRangeCreatedAtDescId (start: int) (endExclusive: int) : TxnStep<EventLog list> =",
        source
      )

      Assert.Contains("let limit = max 0 (endExclusive - start)", source)

      Assert.Contains("ORDER BY [created_at] DESC, [id] ASC LIMIT @limit OFFSET @offset", source))

[<Fact>]
let ``generate emits select_range on views`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE event_log (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL,
  body TEXT NOT NULL
) STRICT;

-- mig:ops select_range(created_at)
CREATE VIEW recent_event AS
  SELECT id, created_at, body FROM event_log;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "RecentEvent.fs"))

      Assert.Contains(
        "let selectRangeCreatedAt (start: int) (endExclusive: int) : TxnStep<RecentEvent list> =",
        source
      )

      Assert.Contains("ORDER BY [created_at] ASC LIMIT @limit OFFSET @offset", source))

[<Fact>]
let ``generate refuses select_range unknown column`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops select_range(missing_col)
CREATE TABLE event_log (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  body TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Ok _ -> Assert.Fail "expected error"
    | Error e -> Assert.Contains("unknown column", e))

[<Fact>]
let ``generate emits select_with with rewritten markers`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE student (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  age INTEGER NOT NULL
) STRICT;

-- mig:ops select_with(min_age, max_age)
-- mig:int64 min_age
-- mig:int64 max_age
CREATE VIEW student_age_range AS
  SELECT id, name, age
  FROM student
  WHERE age >= /*@min_age*/0
    AND age < /*@max_age*/999;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "StudentAgeRange.fs"))

      Assert.Contains("let selectWith (minAge: int64) (maxAge: int64) : TxnStep<StudentAgeRange list> =", source)

      Assert.Contains("\"@min_age\", box (minAge)", source)
      Assert.Contains("\"@max_age\", box (maxAge)", source)
      Assert.Contains("@min_age", source)
      Assert.Contains("@max_age", source)
      Assert.DoesNotContain("/*@min_age*/", source)
      Assert.DoesNotContain("FROM [student_age_range]", source))

[<Fact>]
let ``generate select_with infers types from literals`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE item (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  price REAL NOT NULL
) STRICT;

-- mig:ops select_with(pattern, min_price)
CREATE VIEW item_search AS
  SELECT id, name, price
  FROM item
  WHERE name LIKE /*@pattern*/'%'
    AND price >= /*@min_price*/0.0;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "ItemSearch.fs"))

      Assert.Contains("let selectWith (pattern: string) (minPrice: float) : TxnStep<ItemSearch list> =", source))

[<Fact>]
let ``generate refuses select_with on tables`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops select_with(x)
CREATE TABLE t (
  id INTEGER NOT NULL PRIMARY KEY,
  x INTEGER NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Ok _ -> Assert.Fail "expected error"
    | Error e -> Assert.Contains("select_with is only allowed on views", e))

[<Fact>]
let ``generate refuses select_with missing marker`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE student (
  id INTEGER NOT NULL PRIMARY KEY,
  age INTEGER NOT NULL
) STRICT;

-- mig:ops select_with(min_age, max_age)
CREATE VIEW student_age_range AS
  SELECT id, age FROM student WHERE age >= /*@min_age*/0;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Ok _ -> Assert.Fail "expected error"
    | Error e -> Assert.Contains("missing from view markers", e))

[<Fact>]
let ``view columns generate non-option field types`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL
) STRICT;

-- mig:ops select_all, select_by(email)
CREATE VIEW active_user AS SELECT id, email FROM app_user WHERE id > 0;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "ActiveUser.fs"))
      Assert.Contains("Id: int64", source)
      Assert.Contains("Email: string", source)
      Assert.DoesNotContain("string option", source)
      Assert.DoesNotContain("int64 option", source)
      Assert.Contains("selectByEmail (email: string)", source)
      Assert.DoesNotContain("readStringOption", source)
      Assert.DoesNotContain("boxOption", source))

[<Fact>]
let ``generate refuses write ops on views`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL
) STRICT;

-- mig:ops insert, select_all
CREATE VIEW active_user AS SELECT id, email FROM app_user;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Ok _ -> Assert.Fail "expected write-on-view error"
    | Error msg -> Assert.Contains("write op not allowed on view", msg))

[<Fact>]
let ``unannotated tables produce no files`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore
    Directory.CreateDirectory output |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE orphan (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok result ->
      Assert.Equal(0, result.relationCount)
      Assert.Empty result.generatedFiles
      Assert.Empty(Directory.GetFiles(output, "*.fs")))

[<Fact>]
let ``deletes stale auto-generated files only`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore
    Directory.CreateDirectory output |> ignore

    File.WriteAllText(
      Path.Combine(output, "Stale.fs"),
      """// <auto-generated />
module TestApp.Data.Stores.Stale
let x = 1
"""
    )

    File.WriteAllText(
      Path.Combine(output, "HandWritten.fs"),
      """module TestApp.Data.Stores.HandWritten
let y = 2
"""
    )

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops select_all
CREATE TABLE keep_me (id INTEGER NOT NULL PRIMARY KEY) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok result ->
      Assert.Equal(1, result.relationCount)
      Assert.True(File.Exists(Path.Combine(output, "KeepMe.fs")))
      Assert.False(File.Exists(Path.Combine(output, "Stale.fs")))
      Assert.True(File.Exists(Path.Combine(output, "HandWritten.fs"))))

[<Fact>]
let ``generated insert and select roundtrip`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops insert, select_by_id, select_one_by(email)
CREATE TABLE note (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  body TEXT NOT NULL
) STRICT;
"""
    )

    let dbPath = Path.Combine(dir, "app.sqlite")

    match await (migrateScripts dbPath migrations) with
    | Error e -> Assert.Fail e
    | Ok() ->
      let insertSql = "INSERT INTO [note] ([email], [body]) VALUES (@email, @body)"

      let selectSql = "SELECT [id], [email], [body] FROM [note] WHERE [id] = @id LIMIT 1"

      let run =
        dbTxn dbPath {
          do!
            Query.exec insertSql [ "@email", box "a@b.c"; "@body", box "hello" ]
            |> TxnStep.map ignore

          let! id = Query.lastInsertRowId

          let! row =
            Query.queryOne selectSql [ "@id", box id ] (fun r -> r.GetInt64 0, r.GetString 1, r.GetString 2)

          return id, row
        }

      match await run with
      | Error e -> Assert.Fail(string e)
      | Ok(id, Some(rowId, email, body)) ->
        Assert.True(id > 0L)
        Assert.Equal(id, rowId)
        Assert.Equal("a@b.c", email)
        Assert.Equal("hello", body)
      | Ok(_, None) -> Assert.Fail "row not found")
