module CodegenTests

open System
open System.IO
open System.Threading.Tasks
open Xunit
open MigLib
open MigLib.Codegen

let private await (t: Task<'a>) = t.GetAwaiter().GetResult()

let private withTempDir (action: string -> unit) =
  let dir = Path.Combine(Path.GetTempPath(), $"mig-cg-{Guid.NewGuid():N}")
  Directory.CreateDirectory dir |> ignore

  try
    action dir
  finally
    try
      Directory.Delete(dir, true)
    with _ ->
      ()

[<Fact>]
let ``generate emits one file per relation`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001_users.sql"),
      """
-- mig:rel User
-- mig:ops insert, insert_many, select_by_id, select_one_by(email), upsert, upsert_many, delete_by_id
-- mig:bool active
-- mig:datetime created_at
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  active INTEGER NOT NULL,
  created_at TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok result ->
      Assert.Equal(1, result.relationCount)
      Assert.Single result.generatedFiles |> ignore
      let userPath = Path.Combine(output, "User.fs")
      Assert.True(File.Exists userPath)
      let source = File.ReadAllText userPath
      Assert.Contains("// <auto-generated />", source)
      Assert.Contains("module TestApp.Data.Stores.User", source)
      Assert.Contains("type User =", source)
      Assert.Contains("type UserInsert =", source)
      Assert.Contains("let insert ", source)
      Assert.Contains("let insertMany ", source)
      Assert.Contains("let selectById ", source)
      Assert.Contains("let selectOneByEmail ", source)
      Assert.Contains("let upsert ", source)
      Assert.Contains("let upsertMany ", source)
      Assert.Contains("let deleteById ", source)
      Assert.Contains("bool", source)
      Assert.Contains("DateTimeOffset", source))

[<Fact>]
let ``generate emits select_by_or_insert`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops select_by_or_insert(username), select_by_id
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "AppUser.fs"))
      Assert.Contains("let selectByUsernameOrInsert (row: AppUserInsert) : TxnStep<AppUser> =", source)
      Assert.Contains("type AppUserInsert =", source)
      Assert.Contains("INSERT INTO [app_user]", source)
      Assert.Contains("WHERE [username] = @username LIMIT 1", source)
      Assert.Contains("select_by_or_insert failed to load inserted row", source))

[<Fact>]
let ``generate refuses select_by_or_insert on views`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL
) STRICT;

-- mig:ops select_by_or_insert(username)
CREATE VIEW active_user AS SELECT id, username FROM app_user;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Ok _ -> Assert.Fail "expected write op on view to fail"
    | Error e -> Assert.Contains("write op not allowed on view", e))

[<Fact>]
let ``generate emits select_top and select_bottom`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops select_top(created_at, 200), select_bottom(created_at, 10)
CREATE TABLE event_log (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL,
  body TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "EventLog.fs"))
      Assert.Contains("let selectTopCreatedAt200 : TxnStep<EventLog list> =", source)
      Assert.Contains("ORDER BY [created_at] DESC LIMIT 200", source)
      Assert.Contains("let selectBottomCreatedAt10 : TxnStep<EventLog list> =", source)
      Assert.Contains("ORDER BY [created_at] ASC LIMIT 10", source))

[<Fact>]
let ``view columns generate non-option field types`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL
) STRICT;

-- mig:ops select_all, select_by(email)
CREATE VIEW active_user AS SELECT id, email FROM app_user WHERE id > 0;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok _ ->
      let source = File.ReadAllText(Path.Combine(output, "ActiveUser.fs"))
      Assert.Contains("Id: int64", source)
      Assert.Contains("Email: string", source)
      Assert.DoesNotContain("string option", source)
      Assert.DoesNotContain("int64 option", source)
      Assert.Contains("selectByEmail (email: string)", source)
      Assert.DoesNotContain("readStringOption", source)
      Assert.DoesNotContain("boxOption", source))

[<Fact>]
let ``generate refuses write ops on views`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE app_user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL
) STRICT;

-- mig:ops insert, select_all
CREATE VIEW active_user AS SELECT id, email FROM app_user;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Ok _ -> Assert.Fail "expected write-on-view error"
    | Error msg -> Assert.Contains("write op not allowed on view", msg))

[<Fact>]
let ``unannotated tables produce no files`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore
    Directory.CreateDirectory output |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
CREATE TABLE orphan (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL
) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok result ->
      Assert.Equal(0, result.relationCount)
      Assert.Empty result.generatedFiles
      Assert.Empty(Directory.GetFiles(output, "*.fs")))

[<Fact>]
let ``deletes stale auto-generated files only`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    let output = Path.Combine(dir, "Stores")
    Directory.CreateDirectory migrations |> ignore
    Directory.CreateDirectory output |> ignore

    File.WriteAllText(
      Path.Combine(output, "Stale.fs"),
      """// <auto-generated />
module TestApp.Data.Stores.Stale
let x = 1
"""
    )

    File.WriteAllText(
      Path.Combine(output, "HandWritten.fs"),
      """module TestApp.Data.Stores.HandWritten
let y = 2
"""
    )

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops select_all
CREATE TABLE keep_me (id INTEGER NOT NULL PRIMARY KEY) STRICT;
"""
    )

    match generate migrations output "TestApp.Data.Stores" with
    | Error e -> Assert.Fail e
    | Ok result ->
      Assert.Equal(1, result.relationCount)
      Assert.True(File.Exists(Path.Combine(output, "KeepMe.fs")))
      Assert.False(File.Exists(Path.Combine(output, "Stale.fs")))
      Assert.True(File.Exists(Path.Combine(output, "HandWritten.fs"))))

[<Fact>]
let ``generated insert and select roundtrip`` () =
  withTempDir (fun dir ->
    let migrations = Path.Combine(dir, "migrations")
    Directory.CreateDirectory migrations |> ignore

    File.WriteAllText(
      Path.Combine(migrations, "001.sql"),
      """
-- mig:ops insert, select_by_id, select_one_by(email)
CREATE TABLE note (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  body TEXT NOT NULL
) STRICT;
"""
    )

    let dbPath = Path.Combine(dir, "app.sqlite")

    match await (migrateScripts dbPath migrations) with
    | Error e -> Assert.Fail e
    | Ok() ->
      let insertSql = "INSERT INTO [note] ([email], [body]) VALUES (@email, @body)"

      let selectSql = "SELECT [id], [email], [body] FROM [note] WHERE [id] = @id LIMIT 1"

      let run =
        dbTxn dbPath {
          do!
            Query.exec insertSql [ "@email", box "a@b.c"; "@body", box "hello" ]
            |> TxnStep.map ignore

          let! id = Query.lastInsertRowId

          let! row =
            Query.queryOne selectSql [ "@id", box id ] (fun r -> r.GetInt64 0, r.GetString 1, r.GetString 2)

          return id, row
        }

      match await run with
      | Error e -> Assert.Fail(string e)
      | Ok(id, Some(rowId, email, body)) ->
        Assert.True(id > 0L)
        Assert.Equal(id, rowId)
        Assert.Equal("a@b.c", email)
        Assert.Equal("hello", body)
      | Ok(_, None) -> Assert.Fail "row not found")
