module Test.Codegen.ExecutionTests

open System
open System.Diagnostics
open System.IO

open MigLib.Codegen.Execution
open MigLib.Codegen.Inputs
open MigLib.Codegen.QueryGeneratorTableGenerate
open MigLib.Codegen.QueryGeneratorViewGenerate
open MigLib.Schema.Types
open MigLib.Types
open MigLib.Resolution.Types
open Xunit

let private createTempDir name =
  let path = Path.Combine(Path.GetTempPath(), $"{name}_{Guid.NewGuid()}")

  Directory.CreateDirectory path |> ignore
  path

let private writeFile (path: string) (text: string) =
  let directory = Path.GetDirectoryName path

  if not (String.IsNullOrWhiteSpace directory) then
    Directory.CreateDirectory directory |> ignore

  File.WriteAllText(path, text)

let private makeInputs tempDir =
  let runtimeProjectPath = Path.Combine(tempDir, "Runtime.fsproj")
  let schemaDirectory = Path.Combine(tempDir, "MigSchema")

  let schemaProjectPath = Path.Combine(schemaDirectory, "MigSchema.fsproj")

  let outputPath = Path.Combine(tempDir, "Db.fs")

  writeFile
    runtimeProjectPath
    "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><RootNamespace>RuntimeRoot</RootNamespace></PropertyGroup></Project>"

  writeFile
    schemaProjectPath
    "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><RootNamespace>TestCodegenSchema</RootNamespace></PropertyGroup></Project>"

  let project =
    { runtimeProjectPath = runtimeProjectPath
      runtimeProjectDirectory = tempDir
      runtimeProjectName = "Runtime"
      schemaProjectPath = schemaProjectPath
      schemaDirectory = schemaDirectory }

  { project = project
    schemaAssembly =
      { project = project
        assemblyName = "Test"
        assemblyPath = typeof<TestCodegenSchema.MigSchema.Marker>.Assembly.Location }
    outputPath = outputPath }

let private assertRegularErrorContains expectedText result =
  match result with
  | Error(MigError.Regular message) -> Assert.Contains(expectedText, message)
  | Error error -> failwith $"Expected MigError.Regular, got: {error}"
  | Ok value -> failwith $"Expected error, got: {value}"

let private buildCSharpAssembly tempDir sourceText =
  let projectDir = Path.Combine(tempDir, "SchemaAssembly")
  let projectPath = Path.Combine(projectDir, "SchemaAssembly.csproj")
  let sourcePath = Path.Combine(projectDir, "Schema.cs")
  let migLibPath = typeof<CodegenResult>.Assembly.Location

  writeFile
    projectPath
    $"""<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><Reference Include="MigLib"><HintPath>{migLibPath}</HintPath></Reference></ItemGroup></Project>"""

  writeFile sourcePath sourceText

  let startInfo =
    ProcessStartInfo(
      FileName = "dotnet",
      Arguments = $"build \"{projectPath}\" --nologo -v:q",
      RedirectStandardOutput = true,
      RedirectStandardError = true,
      UseShellExecute = false
    )

  startInfo.WorkingDirectory <- projectDir

  use proc = Process.Start startInfo
  let stdout = proc.StandardOutput.ReadToEnd()
  let stderr = proc.StandardError.ReadToEnd()
  proc.WaitForExit()

  if proc.ExitCode <> 0 then
    failwith $"Expected fixture assembly to build. stdout: {stdout}\nstderr: {stderr}"

  Path.Combine(projectDir, "bin", "Debug", "net10.0", "SchemaAssembly.dll")

[<Fact>]
let ``runCodegen writes Db fs with metadata types and CRUD helpers`` () =
  let tempDir = createTempDir "mig_codegen_execution"

  try
    let inputs = makeInputs tempDir

    match runCodegen inputs with
    | Ok result ->
      Assert.Equal(Path.Combine(tempDir, "Db.fs"), result.outputPath)
      Assert.Equal("TestGeneratedDb.Db", result.generatedModuleName)
      Assert.Equal<string list>([ Path.Combine(tempDir, "Db.fs") ], result.generatedFiles)

      let generated = File.ReadAllText result.outputPath

      Assert.StartsWith("// <auto-generated />", generated)
      Assert.Contains("// This file was generated by MigLib. Do not edit manually.", generated)
      Assert.Contains("[<System.CodeDom.Compiler.GeneratedCode(\"MigLib\",", generated)
      Assert.Contains("module TestGeneratedDb.Db", generated)
      Assert.Contains("open MigLib.Generated", generated)
      Assert.DoesNotContain("open MigLib.Codegen.Helpers", generated)
      Assert.DoesNotContain("open MigLib.Runtime", generated)
      Assert.Contains("let GeneratedSchema", generated)
      Assert.Contains("dbApp = \"TestGeneratedDb\"", generated)
      Assert.Contains("defaultDbInstance = \"main\"", generated)
      Assert.DoesNotContain("DbFileForInstance", generated)
      Assert.DoesNotContain("let DbFile", generated)
      Assert.Contains("schemaHash =", generated)
      Assert.DoesNotContain("SchemaIdentity", generated)
      Assert.Contains("schema =", generated)
      Assert.Contains("codegen_fixture", generated)
      Assert.Contains("type CodegenFixture =", generated)
      Assert.Contains("type CodegenFixtureView =", generated)
      Assert.Contains("type CodegenFixtureViewA =", generated)
      Assert.Contains("type LedgerAccount =", generated)
      Assert.Contains("type Invoice =", generated)
      Assert.Contains("type NewPerson =", generated)
      Assert.Contains("type Person =", generated)
      Assert.Contains("table = \"person\"", generated)
      Assert.Contains("columns = [ \"owner_id\" ]", generated)
      Assert.Contains("refTable = \"person\"", generated)
      Assert.Contains("Expr.String \"revenue\"", generated)
      Assert.Contains("Expr.Real 10", generated)

      Assert.True(
        generated.IndexOf("name = \"codegen_fixture_view\"") < generated.IndexOf("name = \"codegen_fixture_view_a\""),
        "GeneratedSchema.views should render dependency views before dependent views."
      )

      Assert.Contains("name = \"codegen_fixture_view_a\"", generated)
      Assert.Contains("dependencies = [ \"codegen_fixture_view\" ]", generated)
      Assert.Contains("| Person.Base(id, _) -> id", generated)
      Assert.Contains("| Person.WithEmail(id, _, _) -> id", generated)
      Assert.Contains("| Person.Base _ -> None", generated)
      Assert.Contains("| Person.WithEmail(_, _, email) -> Some email", generated)
      Assert.DoesNotContain("data.Email", generated)
      Assert.DoesNotContain("data.Id", generated)
      Assert.Contains("static member Upsert (item: Person)", generated)
      Assert.Contains("| Person.WithEmail(id, name, email) -> NewPerson.WithEmail(id, name, email)", generated)
      Assert.Contains("|> fun newItem ->", generated)
      Assert.Contains("static member Insert", generated)
      Assert.Contains("static member InsertOrIgnore", generated)
      Assert.Contains("static member SelectById", generated)
      Assert.Contains("static member SelectAll", generated)
      Assert.Contains("static member SelectOne", generated)
      Assert.Contains("static member SelectOneByNameOrderByAgeDesc", generated)
      Assert.Contains("static member SelectOneByNameOrderByIdDesc", generated)
      Assert.Contains("static member Update", generated)
      Assert.Contains("static member Delete", generated)
      Assert.Contains("static member DeleteAdults", generated)
      Assert.Contains("DELETE FROM codegen_fixture WHERE age >= @age AND name LIKE @name OR name LIKE @name", generated)
      Assert.Contains("static member DeleteAll", generated)
      Assert.Contains("static member SelectByName", generated)
      Assert.Contains("WHERE name = @name ORDER BY age DESC", generated)
      Assert.Contains("WHERE name = @name ORDER BY age DESC LIMIT 1", generated)
      Assert.Contains("FROM codegen_fixture_view WHERE name = @name ORDER BY id DESC LIMIT 1", generated)
      Assert.Contains("static member SelectNameLike", generated)
      Assert.Contains("static member SelectAdults", generated)
      Assert.Contains("WHERE age >= @age AND name LIKE @name OR name LIKE @name ORDER BY name ASC", generated)
      Assert.Contains("cmd.Parameters.AddWithValue(\"@name\", name) |> ignore", generated)
      Assert.Contains("static member SelectNamed", generated)
      Assert.Contains("static member SelectByNameOrInsert", generated)
      Assert.Contains("static member Upsert", generated)
      Assert.DoesNotContain("Recording.", generated)
    | Error error -> failwith $"Expected codegen to run, got: {error}"
  finally
    Directory.Delete(tempDir, true)

[<Fact>]
let ``table codegen fails when SelectWhere references missing parameter column`` () =
  let table =
    { name = "student"
      previousName = None
      dropColumns = []
      columns =
        [ { name = "id"
            previousName = None
            columnType = SqlInteger
            constraints = [ NotNull ]
            enumLikeDu = None
            unitOfMeasure = None } ]
      constraints = []
      queryByAnnotations = []
      queryLikeAnnotations = []
      queryWhereAnnotations =
        [ { name = "Adults"
            whereSql = "age >= @age"
            columns = [ "age" ]
            orderBy = None } ]
      queryByOrCreateAnnotations = []
      selectOneAnnotations = []
      selectOneByAnnotations = []
      insertOrIgnoreAnnotations = []
      deleteWhereAnnotations = []
      deleteAllAnnotations = []
      upsertAnnotations = [] }

  generateTableCode table
  |> function
    | Error message -> Assert.Contains("QueryWhere annotation references non-existent column 'age'", message)
    | Ok generated -> failwith $"Expected SelectWhere validation failure, got: {generated}"

[<Fact>]
let ``table codegen fails when DeleteWhere references missing parameter column`` () =
  let table =
    { name = "student"
      previousName = None
      dropColumns = []
      columns =
        [ { name = "id"
            previousName = None
            columnType = SqlInteger
            constraints = [ NotNull ]
            enumLikeDu = None
            unitOfMeasure = None } ]
      constraints = []
      queryByAnnotations = []
      queryLikeAnnotations = []
      queryWhereAnnotations = []
      queryByOrCreateAnnotations = []
      selectOneAnnotations = []
      selectOneByAnnotations = []
      insertOrIgnoreAnnotations = []
      deleteWhereAnnotations =
        [ { name = "Adults"
            whereSql = "age >= @age"
            columns = [ "age" ] } ]
      deleteAllAnnotations = []
      upsertAnnotations = [] }

  generateTableCode table
  |> function
    | Error message -> Assert.Contains("DeleteWhere annotation references non-existent column 'age'", message)
    | Ok generated -> failwith $"Expected DeleteWhere validation failure, got: {generated}"

[<Fact>]
let ``view codegen fails when DeleteWhere is used on read-only view`` () =
  let view =
    { name = "student_view"
      previousName = None
      sql = "CREATE VIEW student_view AS SELECT id FROM student"
      declaredColumns =
        [ { name = "id"
            columnType = SqlInteger
            enumLikeDu = None
            unitOfMeasure = None } ]
      dependencies = [ "student" ]
      queryByAnnotations = []
      queryLikeAnnotations = []
      queryWhereAnnotations = []
      queryByOrCreateAnnotations = []
      selectOneAnnotations = []
      selectOneByAnnotations = []
      insertOrIgnoreAnnotations = []
      deleteWhereAnnotations =
        [ { name = "ById"
            whereSql = "id = @id"
            columns = [ "id" ] } ]
      deleteAllAnnotations = []
      upsertAnnotations = [] }

  generateViewCode view view.declaredColumns
  |> function
    | Error message -> Assert.Contains("DeleteWhere annotation is not supported on views", message)
    | Ok generated -> failwith $"Expected DeleteWhere view rejection, got: {generated}"

[<Fact>]
let ``runCodegen fails when generated Db namespace attribute is missing`` () =
  let tempDir = createTempDir "mig_codegen_execution_missing_schema_module"

  try
    let inputs = makeInputs tempDir

    let inputs =
      { inputs with
          schemaAssembly =
            { inputs.schemaAssembly with
                assemblyPath = typeof<CodegenResult>.Assembly.Location } }

    runCodegen inputs
    |> assertRegularErrorContains "does not contain a module marked with GeneratedDbNamespaceAttribute"
  finally
    Directory.Delete(tempDir, true)

[<Fact>]
let ``runCodegen fails when generated Db namespace attributes disagree`` () =
  let tempDir = createTempDir "mig_codegen_execution_mismatched_schema_modules"

  try
    let inputs = makeInputs tempDir

    let assemblyPath =
      buildCSharpAssembly
        tempDir
        """
using MigLib.Dsl;

[Attributes.GeneratedDbNamespace("One")]
public static class FirstSchemaModule {}

[Attributes.GeneratedDbNamespace("Two")]
public static class SecondSchemaModule {}
"""

    let inputs =
      { inputs with
          schemaAssembly =
            { inputs.schemaAssembly with
                assemblyPath = assemblyPath } }

    runCodegen inputs
    |> assertRegularErrorContains "different GeneratedDbNamespaceAttribute values"
  finally
    Directory.Delete(tempDir, true)
