module Test.Codegen.ExecutionTests

open System
open System.IO

open MigLib.Codegen.Execution
open MigLib.Codegen.Inputs
open MigLib.Types
open MigLib.Resolution.Types
open Xunit

let private createTempDir name =
  let path = Path.Combine(Path.GetTempPath(), $"{name}_{Guid.NewGuid()}")

  Directory.CreateDirectory path |> ignore
  path

let private writeFile (path: string) (text: string) =
  let directory = Path.GetDirectoryName path

  if not (String.IsNullOrWhiteSpace directory) then
    Directory.CreateDirectory directory |> ignore

  File.WriteAllText(path, text)

let private makeInputs tempDir =
  let runtimeProjectPath = Path.Combine(tempDir, "Runtime.fsproj")
  let domainModelingDirectory = Path.Combine(tempDir, "DomainModeling")

  let domainModelingProjectPath =
    Path.Combine(domainModelingDirectory, "DomainModeling.fsproj")

  let schemaSourcePath = Path.Combine(domainModelingDirectory, "MigSchema.fs")
  let outputPath = Path.Combine(tempDir, "Db.fs")

  writeFile
    runtimeProjectPath
    "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><RootNamespace>RuntimeRoot</RootNamespace></PropertyGroup></Project>"

  writeFile
    domainModelingProjectPath
    "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><RootNamespace>TestCodegenSchema</RootNamespace></PropertyGroup></Project>"

  writeFile
    schemaSourcePath
    "[<MigLib.Dsl.Attributes.GeneratedDbNamespace(\"TestGeneratedDb\")>]\nmodule TestCodegenSchema.MigSchema"

  let project =
    { runtimeProjectPath = runtimeProjectPath
      runtimeProjectDirectory = tempDir
      runtimeProjectName = "Runtime"
      domainModelingProjectPath = domainModelingProjectPath
      domainModelingDirectory = domainModelingDirectory }

  { project = project
    domainModelingAssembly =
      { project = project
        assemblyName = "Test"
        assemblyPath = typeof<TestCodegenSchema.MigSchema.Marker>.Assembly.Location }
    schemaSourcePath = schemaSourcePath
    outputPath = outputPath }

let private assertRegularErrorContains expectedText result =
  match result with
  | Error(MigError.Regular message) -> Assert.Contains(expectedText, message)
  | Error error -> failwith $"Expected MigError.Regular, got: {error}"
  | Ok value -> failwith $"Expected error, got: {value}"

[<Fact>]
let ``runCodegen writes Db fs with metadata types and CRUD helpers`` () =
  let tempDir = createTempDir "mig_codegen_execution"

  try
    let inputs = makeInputs tempDir

    match runCodegen inputs with
    | Ok result ->
      Assert.Equal(Path.Combine(tempDir, "Db.fs"), result.outputPath)
      Assert.Equal("TestGeneratedDb.Db", result.generatedModuleName)
      Assert.Equal<string list>([ Path.Combine(tempDir, "Db.fs") ], result.generatedFiles)

      let generated = File.ReadAllText result.outputPath

      Assert.StartsWith("// <auto-generated />", generated)
      Assert.Contains("// This file was generated by MigLib. Do not edit manually.", generated)
      Assert.Contains("[<System.CodeDom.Compiler.GeneratedCode(\"MigLib\",", generated)
      Assert.Contains("module TestGeneratedDb.Db", generated)
      Assert.Contains("open MigLib.Generated", generated)
      Assert.DoesNotContain("open MigLib.Codegen.Helpers", generated)
      Assert.DoesNotContain("open MigLib.Runtime", generated)
      Assert.Contains("let GeneratedSchema", generated)
      Assert.Contains("dbApp = \"TestGeneratedDb\"", generated)
      Assert.Contains("defaultDbInstance = \"main\"", generated)
      Assert.DoesNotContain("DbFileForInstance", generated)
      Assert.DoesNotContain("let DbFile", generated)
      Assert.Contains("schemaHash =", generated)
      Assert.DoesNotContain("SchemaIdentity", generated)
      Assert.Contains("schema =", generated)
      Assert.Contains("codegen_fixture", generated)
      Assert.Contains("type CodegenFixture =", generated)
      Assert.Contains("type CodegenFixtureView =", generated)
      Assert.Contains("type NewPerson =", generated)
      Assert.Contains("type Person =", generated)
      Assert.Contains("static member Insert", generated)
      Assert.Contains("static member InsertOrIgnore", generated)
      Assert.Contains("static member SelectById", generated)
      Assert.Contains("static member SelectAll", generated)
      Assert.Contains("static member SelectOne", generated)
      Assert.Contains("static member Update", generated)
      Assert.Contains("static member Delete", generated)
      Assert.Contains("static member DeleteAll", generated)
      Assert.Contains("static member SelectByName", generated)
      Assert.Contains("static member SelectNameLike", generated)
      Assert.Contains("static member SelectByNameOrInsert", generated)
      Assert.Contains("static member Upsert", generated)
      Assert.Contains("Recording.recordInsert", generated)
    | Error error -> failwith $"Expected codegen to run, got: {error}"
  finally
    Directory.Delete(tempDir, true)

[<Fact>]
let ``runCodegen fails when generated Db namespace attribute is missing`` () =
  let tempDir = createTempDir "mig_codegen_execution_missing_schema_module"

  try
    let inputs = makeInputs tempDir

    let inputs =
      { inputs with
          domainModelingAssembly =
            { inputs.domainModelingAssembly with
                assemblyPath = typeof<CodegenResult>.Assembly.Location } }

    runCodegen inputs
    |> assertRegularErrorContains "does not contain a module marked with GeneratedDbNamespaceAttribute"
  finally
    Directory.Delete(tempDir, true)
