// <auto-generated />
// This file was generated by MigLib. Do not edit manually.

[<System.CodeDom.Compiler.GeneratedCode("MigLib", "8.0.1+4409fbadd7f52810e292623c92225acfa0a60c45")>]
module ExampleApp.Db

open System
open System.Threading.Tasks
open Microsoft.Data.Sqlite
open MigLib.Generated

let GeneratedSchema: ResolvedGeneratedSchemaModule =
  { schema =
      { measureTypes = []
        inserts = []
        views = []
        tables =
          [ { name = "student"
              previousName = None
              dropColumns = []
              columns =
                [ { name = "id"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints =
                      [ ColumnConstraint.NotNull
                        ColumnConstraint.PrimaryKey
                          { constraintName = None
                            columns = []
                            isAutoincrement = true } ]
                    enumLikeDu = None
                    unitOfMeasure = None }
                  { name = "name"
                    previousName = None
                    columnType = SqlType.SqlText
                    constraints = [ ColumnConstraint.NotNull; ColumnConstraint.Unique [] ]
                    enumLikeDu = None
                    unitOfMeasure = None }
                  { name = "age"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints = [ ColumnConstraint.NotNull; ColumnConstraint.Default(Expr.Integer 18) ]
                    enumLikeDu = None
                    unitOfMeasure = None } ]
              constraints = []
              queryByAnnotations = [ { columns = [ "name" ] } ]
              queryLikeAnnotations = [ { columns = [ "name" ] } ]
              queryByOrCreateAnnotations = [ { columns = [ "name" ] } ]
              selectOneAnnotations = [ SelectOneAnnotation ]
              insertOrIgnoreAnnotations = [ InsertOrIgnoreAnnotation ]
              deleteAllAnnotations = [ DeleteAllAnnotation ]
              upsertAnnotations = [] }
            { name = "student_address"
              previousName = None
              dropColumns = []
              columns =
                [ { name = "student_id"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints =
                      [ ColumnConstraint.NotNull
                        ColumnConstraint.ForeignKey
                          { columns = []
                            refTable = "student"
                            refColumns = [ "id" ]
                            onDelete = None
                            onUpdate = None }
                        ColumnConstraint.PrimaryKey
                          { constraintName = None
                            columns = []
                            isAutoincrement = false } ]
                    enumLikeDu = None
                    unitOfMeasure = None }
                  { name = "address"
                    previousName = None
                    columnType = SqlType.SqlText
                    constraints = [ ColumnConstraint.NotNull ]
                    enumLikeDu = None
                    unitOfMeasure = None } ]
              constraints = []
              queryByAnnotations = []
              queryLikeAnnotations = []
              queryByOrCreateAnnotations = []
              selectOneAnnotations = []
              insertOrIgnoreAnnotations = []
              deleteAllAnnotations = []
              upsertAnnotations = [] } ]
        indexes = []
        triggers = [] }
    schemaHash = "1aadf3d626409dd7"
    dbApp = "ExampleApp"
    defaultDbInstance = "main" }

[<RequireQualifiedAccess>]
type NewStudent =
  | Base of Name: string * Age: int64
  | WithAddress of Name: string * Age: int64 * Address: string


[<RequireQualifiedAccess>]
type Student =
  | Base of Id: int64 * Name: string * Age: int64
  | WithAddress of Id: int64 * Name: string * Age: int64 * Address: string


type Student with
  member this.Address: string option =
    match this with
    | Student.Base _ -> None
    | Student.WithAddress(_, _, _, address) -> Some address

  member this.Age: int64 =
    match this with
    | Student.Base(_, _, age) -> age
    | Student.WithAddress(_, _, age, _) -> age

  member this.Id: int64 =
    match this with
    | Student.Base(id, _, _) -> id
    | Student.WithAddress(id, _, _, _) -> id

  member this.Name: string =
    match this with
    | Student.Base(_, name, _) -> name
    | Student.WithAddress(_, name, _, _) -> name


type Student with
  static member Insert (item: NewStudent) (tx: SqliteTransaction) : Task<Result<int64, SqliteException>> =
    task {
      try
        match item with
        | NewStudent.Base(name, age) ->
          return!
            executeInsert
              "INSERT INTO student (name, age) VALUES (@name, @age)"
              (fun cmd ->
                cmd.Parameters.AddWithValue("@name", name) |> ignore
                cmd.Parameters.AddWithValue("@age", age) |> ignore)
              tx
              (fun studentId -> task { return Ok studentId })
        | NewStudent.WithAddress(name, age, address) ->
          let! baseInsertResult =
            executeInsert
              "INSERT INTO student (name, age) VALUES (@name, @age)"
              (fun cmd ->
                cmd.Parameters.AddWithValue("@name", name) |> ignore
                cmd.Parameters.AddWithValue("@age", age) |> ignore)
              tx
              (fun studentId -> task { return Ok studentId })

          match baseInsertResult with
          | Error ex -> return Error ex
          | Ok studentId ->
            return!
              executeWrite
                "INSERT INTO student_address (student_id, address) VALUES (@student_id, @address)"
                (fun cmd ->
                  cmd.Parameters.AddWithValue("@student_id", studentId) |> ignore
                  cmd.Parameters.AddWithValue("@address", address) |> ignore)
                tx
                (fun _ -> task { return Ok studentId })
      with :? SqliteException as ex ->
        return Error ex
    }

  static member InsertOrIgnore
    (item: NewStudent)
    (tx: SqliteTransaction)
    : Task<Result<int64 option, SqliteException>> =
    task {
      try
        match item with
        | NewStudent.Base(name, age) ->
          return!
            executeInsertOrIgnore
              "INSERT OR IGNORE INTO student (name, age) VALUES (@name, @age)"
              (fun cmd ->
                cmd.Parameters.AddWithValue("@name", name) |> ignore
                cmd.Parameters.AddWithValue("@age", age) |> ignore)
              tx
              (fun studentId -> task { return Ok studentId })
        | NewStudent.WithAddress(name, age, address) ->
          let! baseInsertResult =
            executeInsertOrIgnore
              "INSERT OR IGNORE INTO student (name, age) VALUES (@name, @age)"
              (fun cmd ->
                cmd.Parameters.AddWithValue("@name", name) |> ignore
                cmd.Parameters.AddWithValue("@age", age) |> ignore)
              tx
              (fun studentId -> task { return Ok studentId })

          match baseInsertResult with
          | Error ex -> return Error ex
          | Ok None -> return Ok None
          | Ok(Some studentId) ->
            return!
              executeWrite
                "INSERT INTO student_address (student_id, address) VALUES (@student_id, @address)"
                (fun cmd ->
                  cmd.Parameters.AddWithValue("@student_id", studentId) |> ignore
                  cmd.Parameters.AddWithValue("@address", address) |> ignore)
                tx
                (fun _ -> task { return Ok(Some studentId) })
      with :? SqliteException as ex ->
        return Error ex
    }

  static member SelectAll(tx: SqliteTransaction) : Task<Result<Student list, SqliteException>> =
    queryList
      "SELECT student.id, student.name, student.age, ext0.address\n         FROM student\n         LEFT JOIN student_address ext0 ON student.id = ext0.student_id"
      (fun _ -> ())
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member SelectById (id: int64) (tx: SqliteTransaction) : Task<Result<Student option, SqliteException>> =
    querySingle
      "SELECT student.id, student.name, student.age, ext0.address\n         FROM student\n         LEFT JOIN student_address ext0 ON student.id = ext0.student_id\n         WHERE student.id = @id"
      (fun cmd -> cmd.Parameters.AddWithValue("@id", id) |> ignore)
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member SelectOne(tx: SqliteTransaction) : Task<Result<Student option, SqliteException>> =
    querySingle
      "SELECT student.id, student.name, student.age, ext0.address\n         FROM student\n         LEFT JOIN student_address ext0 ON student.id = ext0.student_id\n         LIMIT 1"
      (fun _ -> ())
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member Update (item: Student) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    task {
      try
        match item with
        | Student.Base(id, name, age) ->
          let deleteExtensions () =
            sequenceUnitResults
              [ (fun () ->
                  executeWriteUnit
                    "DELETE FROM student_address WHERE student_id = @student_id"
                    (fun cmd -> cmd.Parameters.AddWithValue("@student_id", id) |> ignore)
                    tx) ]

          return!
            sequenceUnitResults
              [ (fun () ->
                  executeWriteUnit
                    "UPDATE student SET name = @name, age = @age WHERE id = @id"
                    (fun cmd ->
                      cmd.Parameters.AddWithValue("@id", id) |> ignore
                      cmd.Parameters.AddWithValue("@name", name) |> ignore
                      cmd.Parameters.AddWithValue("@age", age) |> ignore)
                    tx)
                (fun () -> deleteExtensions ()) ]
        | Student.WithAddress(id, name, age, address) ->
          let deleteOtherExtensions () = sequenceUnitResults []

          return!
            sequenceUnitResults
              [ (fun () ->
                  executeWriteUnit
                    "UPDATE student SET name = @name, age = @age WHERE id = @id"
                    (fun cmd ->
                      cmd.Parameters.AddWithValue("@id", id) |> ignore
                      cmd.Parameters.AddWithValue("@name", name) |> ignore
                      cmd.Parameters.AddWithValue("@age", age) |> ignore)
                    tx)
                (fun () ->
                  executeWriteUnit
                    "INSERT OR REPLACE INTO student_address (student_id, address) VALUES (@student_id, @address)"
                    (fun cmd ->
                      cmd.Parameters.AddWithValue("@student_id", id) |> ignore
                      cmd.Parameters.AddWithValue("@address", address) |> ignore)
                    tx)
                (fun () -> deleteOtherExtensions ()) ]
      with :? SqliteException as ex ->
        return Error ex
    }

  static member Delete (id: int64) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    executeWriteUnit
      "DELETE FROM student WHERE id = @id"
      (fun cmd -> cmd.Parameters.AddWithValue("@id", id) |> ignore)
      tx

  static member DeleteAll(tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    executeWriteUnit "DELETE FROM student" (fun _ -> ()) tx

  static member SelectByName (name: string) (tx: SqliteTransaction) : Task<Result<Student list, SqliteException>> =
    queryList
      "SELECT b.id, b.name, b.age, eaddress.address\n        FROM student AS b\n        LEFT JOIN student_address AS eaddress ON b.id = eaddress.student_id\n        WHERE name = @name"
      (fun cmd -> cmd.Parameters.AddWithValue("@name", name) |> ignore)
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member SelectNameLike (name: string) (tx: SqliteTransaction) : Task<Result<Student list, SqliteException>> =
    queryList
      "SELECT b.id, b.name, b.age, eaddress.address\n        FROM student AS b\n        LEFT JOIN student_address AS eaddress ON b.id = eaddress.student_id\n        WHERE name LIKE \'%\' || @name || \'%\'"
      (fun cmd -> cmd.Parameters.AddWithValue("@name", name) |> ignore)
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member SelectByNameOrInsert
    (newItem: NewStudent)
    (tx: SqliteTransaction)
    : Task<Result<Student, SqliteException>> =
    let name =
      match newItem with
      | NewStudent.Base(name, age) -> name
      | NewStudent.WithAddress(name, age, address) -> name

    let select () =
      querySingle
        "SELECT b.id, b.name, b.age, eaddress.address FROM student b\n      LEFT JOIN student_address eaddress ON b.id = eaddress.student_id\n      WHERE name = @name LIMIT 1"
        (fun cmd -> cmd.Parameters.AddWithValue("@name", name) |> ignore)
        (fun reader ->
          let hasAddress = not (reader.IsDBNull 3) in

          match hasAddress with
          | true ->
            Student.WithAddress(
              Id = reader.GetInt64 0,
              Name = reader.GetString 1,
              Age = reader.GetInt64 2,
              Address = reader.GetString 3
            )
          | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
        tx

    querySingleOrInsert select (fun () -> Student.Insert newItem tx)
