module Mig.HotMigration

type MigrationStatusReport = HotMigrationTypes.MigrationStatusReport
type OldDatabaseStatusReport = HotMigrationTypes.OldDatabaseStatusReport
type NewDatabaseStatusReport = HotMigrationTypes.NewDatabaseStatusReport
type CutoverResult = HotMigrationTypes.CutoverResult
type MigrateResult = HotMigrationTypes.MigrateResult
type InitResult = HotMigrationTypes.InitResult
type SchemaIdentity = HotMigrationTypes.SchemaIdentity
type MigratePlanReport = HotMigrationTypes.MigratePlanReport
type DrainResult = HotMigrationTypes.DrainResult
type ArchiveOldResult = HotMigrationTypes.ArchiveOldResult
type ResetMigrationResult = HotMigrationTypes.ResetMigrationResult
type ResetMigrationPlan = HotMigrationTypes.ResetMigrationPlan

let internal analyzeNonTableConsistency =
  HotMigrationReporting.analyzeNonTableConsistency

let getMigratePlanWithSchema = HotMigrationReporting.getMigratePlanWithSchema
let getStatus = HotMigrationReporting.getStatus
let getNewDatabaseStatus = HotMigrationReporting.getNewDatabaseStatus
let getOldDatabaseStatus = HotMigrationReporting.getOldDatabaseStatus

let runMigrateWithSchema = HotMigrationMigration.runMigrateWithSchema
let runOfflineMigrateWithSchema = HotMigrationMigration.runOfflineMigrateWithSchema
let runInitWithSchema = HotMigrationMigration.runInitWithSchema
let inferPreviousDatabasePath = HotMigrationMigration.inferPreviousDatabasePath
let startServiceWithPolling = HotMigrationMigration.startServiceWithPolling
let startService = HotMigrationMigration.startService
let runDrain = HotMigrationMigration.runDrain

let runArchiveOld = HotMigrationAdmin.runArchiveOld
let getResetMigrationPlan = HotMigrationAdmin.getResetMigrationPlan
let runResetMigration = HotMigrationAdmin.runResetMigration
let runCutover = HotMigrationAdmin.runCutover
let runCutoverWithOldSafety = HotMigrationAdmin.runCutoverWithOldSafety
