// <auto-generated />
// Generated by mig codegen. Do not edit by hand.

module Example.Db.Migration

open System.Threading.Tasks
open MigLib

let private expectedSchema =
    """-- mig:rel Student
-- mig:ops insert, select_by_id, select_one_by(name), select_all, upsert, delete_by_id
CREATE TABLE student (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  age INTEGER NOT NULL
) STRICT;
"""

let private migrationSql = """"""

/// Apply the compiled snapshot (empty DB) or hop + catalog check.
let migrate (dbPath: string) : Task<Result<DbTxnBuilder, MigError>> =
    Migrate.migrate dbPath expectedSchema migrationSql
