// <auto-generated />
// Generated by mig codegen. Do not edit by hand.

module Example.Db.Student

open System
open Microsoft.Data.Sqlite
open MigLib
open MigLib.Query
open MigLib.Runtime.TxnStep

type Student =
  {
    Id: int64
    Name: string
    Age: int64
  }

type StudentInsert =
  {
    Name: string
    Age: int64
  }

let private mapRow (r: SqliteDataReader) : Student =
  {
    Id = Query.readInt64 r 0
    Name = Query.readString r 1
    Age = Query.readInt64 r 2
  }

let insert (row: StudentInsert) : TxnStep<int64> =
  let parameters =
    [
      "@name", box (row.Name)
      "@age", box (row.Age)
    ]
  TxnStep.bind (Query.exec "INSERT INTO [student] ([name], [age]) VALUES (@name, @age)" parameters) (fun _ -> Query.lastInsertRowId)

let selectById (id: int64) : TxnStep<Student option> =
  let parameters = [ "@id", box (id) ]
  Query.queryOne "SELECT [id], [name], [age] FROM [student] WHERE [id] = @id LIMIT 1" parameters mapRow

let selectOneByName (name: string) : TxnStep<Student option> =
  let parameters =
    [
      "@name", box (name)
    ]
  Query.queryOne "SELECT [id], [name], [age] FROM [student] WHERE [name] = @name LIMIT 1" parameters mapRow

let selectAll : TxnStep<Student list> =
  Query.queryList "SELECT [id], [name], [age] FROM [student]" [] mapRow

let upsert (row: Student) : TxnStep<int> =
  let parameters =
    [
      "@id", box (row.Id)
      "@name", box (row.Name)
      "@age", box (row.Age)
    ]
  Query.exec "INSERT INTO [student] ([id], [name], [age]) VALUES (@id, @name, @age) ON CONFLICT([id]) DO UPDATE SET [name] = excluded.[name], [age] = excluded.[age]" parameters

let deleteById (id: int64) : TxnStep<int> =
  let parameters = [ "@id", box (id) ]
  Query.exec "DELETE FROM [student] WHERE [id] = @id" parameters

