namespace MigLib.Codegen

module Generate =
  open System
  open System.IO
  open System.Threading.Tasks
  open MigLib.Migrate
  open MigLib.Codegen

  let private withTempDb (action: string -> Result<'a, string>) : Result<'a, string> =
    let path =
      Path.Combine(Path.GetTempPath(), "mig-codegen-" + Guid.NewGuid().ToString("N") + ".sqlite")

    try
      let result = action path

      try
        if File.Exists path then
          File.Delete path
      with _ ->
        ()

      for suffix in [ "-wal"; "-shm" ] do
        let side = path + suffix

        try
          if File.Exists side then
            File.Delete side
        with _ ->
          ()

      result
    with ex ->
      Error ex.Message

  let private await (t: Task<'a>) = t.GetAwaiter().GetResult()

  let private isAutoGenerated (path: string) =
    try
      use reader = new StreamReader(path)
      let first = reader.ReadLine()
      not (isNull first) && first.Trim() = Emit.autoGeneratedMarker.Trim()
    with _ ->
      false

  let private deleteStaleGenerated (outputDir: string) (keepNames: Set<string>) =
    if Directory.Exists outputDir then
      for path in Directory.GetFiles(outputDir, "*.fs") do
        let name = Path.GetFileNameWithoutExtension path

        if not (keepNames.Contains name) && isAutoGenerated path then
          File.Delete path

  /// Generate one F# module file per annotated relation into <paramref name="outputDir"/>,
  /// plus Migrations.fs with ordered SQL scripts as F# string constants for runtime migrateScripts.
  let generate (migrationsDir: string) (outputDir: string) (namespaceName: string) : Result<CodegenResult, string> =
    if String.IsNullOrWhiteSpace migrationsDir then
      Error "migrations directory is required"
    elif String.IsNullOrWhiteSpace outputDir then
      Error "output directory is required"
    elif String.IsNullOrWhiteSpace namespaceName then
      Error "namespace is required"
    elif not (Directory.Exists migrationsDir) then
      Error $"migrations directory not found: {migrationsDir}"
    else
      match loadScriptsFromDirectory migrationsDir with
      | Error e -> Error e
      | Ok scripts ->
        withTempDb (fun dbPath ->
          match await (migrateScripts dbPath scripts) with
          | Error e -> Error $"failed to apply migrations: {e}"
          | Ok() ->
            match Introspection.introspect dbPath with
            | Error e -> Error $"introspection failed: {e}"
            | Ok schema ->
              match Annotations.parseMigrationsDirectory migrationsDir with
              | Error e -> Error e
              | Ok annotations ->
                let fullDir = Path.GetFullPath outputDir
                Directory.CreateDirectory fullDir |> ignore

                match
                  if annotations.IsEmpty then
                    Ok []
                  else
                    Validation.merge schema annotations
                with
                | Error e -> Error e
                | Ok relations ->
                  match relations |> List.tryFind (fun r -> r.fsName = Emit.migrationsModuleName) with
                  | Some _ ->
                    Error
                      $"relation F# name '{Emit.migrationsModuleName}' is reserved for embedded migration scripts; use -- mig:rel OtherName"
                  | None ->
                    let written = ResizeArray<string>()

                    for rel in relations |> List.sortBy _.fsName do
                      let filePath = Path.Combine(fullDir, rel.fsName + ".fs")
                      let source = Emit.emitRelationFile namespaceName rel
                      File.WriteAllText(filePath, source)
                      written.Add(Path.GetFullPath filePath)

                    let migrationsPath = Path.Combine(fullDir, Emit.migrationsModuleName + ".fs")
                    let migrationsSource = Emit.emitMigrationsFile namespaceName scripts
                    File.WriteAllText(migrationsPath, migrationsSource)
                    written.Add(Path.GetFullPath migrationsPath)

                    let keep =
                      relations
                      |> List.map _.fsName
                      |> Set.ofList
                      |> Set.add Emit.migrationsModuleName

                    deleteStaleGenerated fullDir keep

                    Ok
                      { outputDir = fullDir
                        namespaceName = namespaceName
                        relationCount = relations.Length
                        generatedFiles = written |> List.ofSeq })
