// <auto-generated />
// This file was generated by MigLib. Do not edit manually.

[<System.CodeDom.Compiler.GeneratedCode("MigLib", "9.0.0+e256243c0cc8c3ffefa98c16e86efc71a86057e7")>]
module ExampleApp.Db

open System
open System.Threading.Tasks
open Microsoft.Data.Sqlite
open MigLib.Generated

let GeneratedSchema: ResolvedGeneratedSchemaModule =
  {
    schema =
      {
        measureTypes = []
        inserts =
          [
            {
              table = "course"
              columns = [ "id"; "code"; "title" ]
              values = [ [ Expr.Integer 0; Expr.String "intro-fsharp"; Expr.String "Intro to F#" ] ]
            }
          ]
        views =
          [
            {
              name = "enrollment_summary"
              previousName = None
              sql =
                "CREATE VIEW enrollment_summary AS 
SELECT
  enrollment.id,
  student.name AS student_name,
  course.code AS course_code
FROM enrollment
JOIN student ON student.id = enrollment.student_id
JOIN course ON course.id = enrollment.course_id
"
              declaredColumns =
                [
                  {
                    name = "id"
                    columnType = SqlType.SqlInteger
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "student_name"
                    columnType = SqlType.SqlText
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "course_code"
                    columnType = SqlType.SqlText
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                ]
              dependencies = [ "enrollment"; "student"; "course" ]
              queryByAnnotations = []
              queryLikeAnnotations = []
              queryWhereAnnotations = []
              queryByOrCreateAnnotations = []
              selectOneAnnotations = []
              selectOneByAnnotations = []
              insertOrIgnoreAnnotations = []
              deleteWhereAnnotations = []
              deleteAllAnnotations = []
              upsertAnnotations = []
            }
            {
              name = "student18"
              previousName = None
              sql =
                "CREATE VIEW student18 AS 
SELECT id, name, age FROM student
WHERE age >= 18
"
              declaredColumns =
                [
                  {
                    name = "id"
                    columnType = SqlType.SqlInteger
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "name"
                    columnType = SqlType.SqlText
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "age"
                    columnType = SqlType.SqlInteger
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                ]
              dependencies = [ "student" ]
              queryByAnnotations = []
              queryLikeAnnotations = []
              queryWhereAnnotations = []
              queryByOrCreateAnnotations = []
              selectOneAnnotations = []
              selectOneByAnnotations = []
              insertOrIgnoreAnnotations = []
              deleteWhereAnnotations = []
              deleteAllAnnotations = []
              upsertAnnotations = []
            }
            {
              name = "student18a"
              previousName = None
              sql =
                "CREATE VIEW student18a AS 
SELECT id, name, age FROM student18
WHERE name like 'A%'
"
              declaredColumns =
                [
                  {
                    name = "id"
                    columnType = SqlType.SqlInteger
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "name"
                    columnType = SqlType.SqlText
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "age"
                    columnType = SqlType.SqlInteger
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                ]
              dependencies = [ "student18" ]
              queryByAnnotations = []
              queryLikeAnnotations = []
              queryWhereAnnotations = []
              queryByOrCreateAnnotations = []
              selectOneAnnotations = []
              selectOneByAnnotations = []
              insertOrIgnoreAnnotations = []
              deleteWhereAnnotations = []
              deleteAllAnnotations = []
              upsertAnnotations = []
            }
          ]
        tables =
          [
            {
              name = "course"
              previousName = None
              dropColumns = []
              columns =
                [
                  {
                    name = "id"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints =
                      [
                        ColumnConstraint.NotNull
                        ColumnConstraint.PrimaryKey
                          {
                            constraintName = None
                            columns = []
                            isAutoincrement = true
                          }
                      ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "code"
                    previousName = None
                    columnType = SqlType.SqlText
                    constraints = [ ColumnConstraint.NotNull; ColumnConstraint.Unique [] ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "title"
                    previousName = None
                    columnType = SqlType.SqlText
                    constraints = [ ColumnConstraint.NotNull ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                ]
              constraints = []
              queryByAnnotations = [ { columns = [ "code" ]; orderBy = None } ]
              queryLikeAnnotations = []
              queryWhereAnnotations = []
              queryByOrCreateAnnotations = []
              selectOneAnnotations = []
              selectOneByAnnotations = []
              insertOrIgnoreAnnotations = []
              deleteWhereAnnotations = []
              deleteAllAnnotations = []
              upsertAnnotations = []
            }
            {
              name = "enrollment"
              previousName = None
              dropColumns = []
              columns =
                [
                  {
                    name = "id"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints =
                      [
                        ColumnConstraint.NotNull
                        ColumnConstraint.PrimaryKey
                          {
                            constraintName = None
                            columns = []
                            isAutoincrement = true
                          }
                      ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "student_id"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints =
                      [
                        ColumnConstraint.NotNull
                        ColumnConstraint.ForeignKey
                          {
                            columns = []
                            refTable = "student"
                            refColumns = [ "id" ]
                            onDelete = None
                            onUpdate = None
                          }
                      ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "course_id"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints =
                      [
                        ColumnConstraint.NotNull
                        ColumnConstraint.ForeignKey
                          {
                            columns = []
                            refTable = "course"
                            refColumns = [ "id" ]
                            onDelete = None
                            onUpdate = None
                          }
                      ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "enrolled_on"
                    previousName = None
                    columnType = SqlType.SqlText
                    constraints = [ ColumnConstraint.NotNull ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                ]
              constraints = []
              queryByAnnotations =
                [
                  {
                    columns = [ "student_id" ]
                    orderBy = None
                  }
                  {
                    columns = [ "course_id" ]
                    orderBy = None
                  }
                ]
              queryLikeAnnotations = []
              queryWhereAnnotations = []
              queryByOrCreateAnnotations = []
              selectOneAnnotations = []
              selectOneByAnnotations = []
              insertOrIgnoreAnnotations = []
              deleteWhereAnnotations = []
              deleteAllAnnotations = []
              upsertAnnotations = []
            }
            {
              name = "student"
              previousName = None
              dropColumns = []
              columns =
                [
                  {
                    name = "id"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints =
                      [
                        ColumnConstraint.NotNull
                        ColumnConstraint.PrimaryKey
                          {
                            constraintName = None
                            columns = []
                            isAutoincrement = true
                          }
                      ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "name"
                    previousName = None
                    columnType = SqlType.SqlText
                    constraints = [ ColumnConstraint.NotNull; ColumnConstraint.Unique [] ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "age"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints = [ ColumnConstraint.NotNull; ColumnConstraint.Default(Expr.Integer 18) ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                ]
              constraints = []
              queryByAnnotations = [ { columns = [ "name" ]; orderBy = None } ]
              queryLikeAnnotations = [ { columns = [ "name" ] } ]
              queryWhereAnnotations = []
              queryByOrCreateAnnotations = [ { columns = [ "name" ] } ]
              selectOneAnnotations = [ SelectOneAnnotation ]
              selectOneByAnnotations = []
              insertOrIgnoreAnnotations = [ InsertOrIgnoreAnnotation ]
              deleteWhereAnnotations =
                [
                  {
                    name = "Adult"
                    whereSql = "age >= @age"
                    columns = [ "age" ]
                  }
                ]
              deleteAllAnnotations = [ DeleteAllAnnotation ]
              upsertAnnotations = [ UpsertAnnotation ]
            }
            {
              name = "student_address"
              previousName = None
              dropColumns = []
              columns =
                [
                  {
                    name = "student_id"
                    previousName = None
                    columnType = SqlType.SqlInteger
                    constraints =
                      [
                        ColumnConstraint.NotNull
                        ColumnConstraint.ForeignKey
                          {
                            columns = []
                            refTable = "student"
                            refColumns = [ "id" ]
                            onDelete = None
                            onUpdate = None
                          }
                        ColumnConstraint.PrimaryKey
                          {
                            constraintName = None
                            columns = []
                            isAutoincrement = false
                          }
                      ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                  {
                    name = "address"
                    previousName = None
                    columnType = SqlType.SqlText
                    constraints = [ ColumnConstraint.NotNull ]
                    enumLikeDu = None
                    unitOfMeasure = None
                  }
                ]
              constraints = []
              queryByAnnotations = []
              queryLikeAnnotations = []
              queryWhereAnnotations = []
              queryByOrCreateAnnotations = []
              selectOneAnnotations = []
              selectOneByAnnotations = []
              insertOrIgnoreAnnotations = []
              deleteWhereAnnotations = []
              deleteAllAnnotations = []
              upsertAnnotations = []
            }
          ]
        indexes = []
        triggers = []
      }
    schemaHash = "e3c6faea8214f25c"
    dbApp = "ExampleApp"
    defaultDbInstance = "main"
  }

[<RequireQualifiedAccess>]
type NewStudent =
  | Base of Name: string * Age: int64
  | WithAddress of Name: string * Age: int64 * Address: string


[<RequireQualifiedAccess>]
type Student =
  | Base of Id: int64 * Name: string * Age: int64
  | WithAddress of Id: int64 * Name: string * Age: int64 * Address: string


type Student with
  member this.Address: string option =
    match this with
    | Student.Base _ -> None
    | Student.WithAddress(_, _, _, address) -> Some address

  member this.Age: int64 =
    match this with
    | Student.Base(_, _, age) -> age
    | Student.WithAddress(_, _, age, _) -> age

  member this.Id: int64 =
    match this with
    | Student.Base(id, _, _) -> id
    | Student.WithAddress(id, _, _, _) -> id

  member this.Name: string =
    match this with
    | Student.Base(_, name, _) -> name
    | Student.WithAddress(_, name, _, _) -> name


type Course =
  {
    Id: int64
    Code: string
    Title: string
  }


type Enrollment =
  {
    Id: int64
    StudentId: int64
    CourseId: int64
    EnrolledOn: string
  }


type EnrollmentSummary =
  {
    Id: int64
    StudentName: string
    CourseCode: string
  }


type Student18 = { Id: int64; Name: string; Age: int64 }


type Student18a = { Id: int64; Name: string; Age: int64 }


type Student with
  static member Insert (item: NewStudent) (tx: SqliteTransaction) : Task<Result<int64, SqliteException>> =
    task {
      try
        match item with
        | NewStudent.Base(name, age) ->
          return!
            executeInsert
              "INSERT INTO student (name, age) VALUES (@name, @age)"
              (fun cmd ->
                cmd.Parameters.AddWithValue("@name", name) |> ignore
                cmd.Parameters.AddWithValue("@age", age) |> ignore)
              tx
              (fun studentId -> task { return Ok studentId })
        | NewStudent.WithAddress(name, age, address) ->
          let! baseInsertResult =
            executeInsert
              "INSERT INTO student (name, age) VALUES (@name, @age)"
              (fun cmd ->
                cmd.Parameters.AddWithValue("@name", name) |> ignore
                cmd.Parameters.AddWithValue("@age", age) |> ignore)
              tx
              (fun studentId -> task { return Ok studentId })

          match baseInsertResult with
          | Error ex -> return Error ex
          | Ok studentId ->
            return!
              executeWrite
                "INSERT INTO student_address (student_id, address) VALUES (@student_id, @address)"
                (fun cmd ->
                  cmd.Parameters.AddWithValue("@student_id", studentId) |> ignore
                  cmd.Parameters.AddWithValue("@address", address) |> ignore)
                tx
                (fun _ -> task { return Ok studentId })
      with :? SqliteException as ex ->
        return Error ex
    }

  static member InsertOrIgnore
    (item: NewStudent)
    (tx: SqliteTransaction)
    : Task<Result<int64 option, SqliteException>> =
    task {
      try
        match item with
        | NewStudent.Base(name, age) ->
          return!
            executeInsertOrIgnore
              "INSERT OR IGNORE INTO student (name, age) VALUES (@name, @age)"
              (fun cmd ->
                cmd.Parameters.AddWithValue("@name", name) |> ignore
                cmd.Parameters.AddWithValue("@age", age) |> ignore)
              tx
              (fun studentId -> task { return Ok studentId })
        | NewStudent.WithAddress(name, age, address) ->
          let! baseInsertResult =
            executeInsertOrIgnore
              "INSERT OR IGNORE INTO student (name, age) VALUES (@name, @age)"
              (fun cmd ->
                cmd.Parameters.AddWithValue("@name", name) |> ignore
                cmd.Parameters.AddWithValue("@age", age) |> ignore)
              tx
              (fun studentId -> task { return Ok studentId })

          match baseInsertResult with
          | Error ex -> return Error ex
          | Ok None -> return Ok None
          | Ok(Some studentId) ->
            return!
              executeWrite
                "INSERT INTO student_address (student_id, address) VALUES (@student_id, @address)"
                (fun cmd ->
                  cmd.Parameters.AddWithValue("@student_id", studentId) |> ignore
                  cmd.Parameters.AddWithValue("@address", address) |> ignore)
                tx
                (fun _ -> task { return Ok(Some studentId) })
      with :? SqliteException as ex ->
        return Error ex
    }

  static member SelectAll(tx: SqliteTransaction) : Task<Result<Student list, SqliteException>> =
    queryList
      "SELECT student.id, student.name, student.age, ext0.address\n         FROM student\n         LEFT JOIN student_address ext0 ON student.id = ext0.student_id"
      (fun _ -> ())
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member SelectById (id: int64) (tx: SqliteTransaction) : Task<Result<Student option, SqliteException>> =
    querySingle
      "SELECT student.id, student.name, student.age, ext0.address\n         FROM student\n         LEFT JOIN student_address ext0 ON student.id = ext0.student_id\n         WHERE student.id = @id"
      (fun cmd -> cmd.Parameters.AddWithValue("@id", id) |> ignore)
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member SelectOne(tx: SqliteTransaction) : Task<Result<Student option, SqliteException>> =
    querySingle
      "SELECT student.id, student.name, student.age, ext0.address\n         FROM student\n         LEFT JOIN student_address ext0 ON student.id = ext0.student_id\n         LIMIT 1"
      (fun _ -> ())
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member Update (item: Student) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    task {
      try
        match item with
        | Student.Base(id, name, age) ->
          let deleteExtensions () =
            sequenceUnitResults
              [
                (fun () ->
                  executeWriteUnit
                    "DELETE FROM student_address WHERE student_id = @student_id"
                    (fun cmd -> cmd.Parameters.AddWithValue("@student_id", id) |> ignore)
                    tx)
              ]

          return!
            sequenceUnitResults
              [
                (fun () ->
                  executeWriteUnit
                    "UPDATE student SET name = @name, age = @age WHERE id = @id"
                    (fun cmd ->
                      cmd.Parameters.AddWithValue("@id", id) |> ignore
                      cmd.Parameters.AddWithValue("@name", name) |> ignore
                      cmd.Parameters.AddWithValue("@age", age) |> ignore)
                    tx)
                (fun () -> deleteExtensions ())
              ]
        | Student.WithAddress(id, name, age, address) ->
          let deleteOtherExtensions () = sequenceUnitResults []

          return!
            sequenceUnitResults
              [
                (fun () ->
                  executeWriteUnit
                    "UPDATE student SET name = @name, age = @age WHERE id = @id"
                    (fun cmd ->
                      cmd.Parameters.AddWithValue("@id", id) |> ignore
                      cmd.Parameters.AddWithValue("@name", name) |> ignore
                      cmd.Parameters.AddWithValue("@age", age) |> ignore)
                    tx)
                (fun () ->
                  executeWriteUnit
                    "INSERT OR REPLACE INTO student_address (student_id, address) VALUES (@student_id, @address)"
                    (fun cmd ->
                      cmd.Parameters.AddWithValue("@student_id", id) |> ignore
                      cmd.Parameters.AddWithValue("@address", address) |> ignore)
                    tx)
                (fun () -> deleteOtherExtensions ())
              ]
      with :? SqliteException as ex ->
        return Error ex
    }

  static member Upsert (item: Student) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    (match item with
     | Student.Base(id, name, age) -> NewStudent.Base(name, age)
     | Student.WithAddress(id, name, age, address) -> NewStudent.WithAddress(name, age, address))
    |> fun newItem ->
      upsertByExisting (fun () -> Student.SelectById item.Id tx) (fun () -> Student.Update item tx) (fun () ->
        Student.Insert newItem tx)

  static member Delete (id: int64) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    executeWriteUnit
      "DELETE FROM student WHERE id = @id"
      (fun cmd -> cmd.Parameters.AddWithValue("@id", id) |> ignore)
      tx

  static member DeleteAll(tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    executeWriteUnit "DELETE FROM student" (fun _ -> ()) tx

  static member DeleteAdult (age: int64) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    executeWriteUnit
      "DELETE FROM student WHERE age >= @age"
      (fun cmd -> cmd.Parameters.AddWithValue("@age", age) |> ignore)
      tx

  static member SelectByName (name: string) (tx: SqliteTransaction) : Task<Result<Student list, SqliteException>> =
    queryList
      "SELECT b.id, b.name, b.age, eaddress.address\n        FROM student AS b\n        LEFT JOIN student_address AS eaddress ON b.id = eaddress.student_id\n        WHERE name = @name"
      (fun cmd -> cmd.Parameters.AddWithValue("@name", name) |> ignore)
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member SelectNameLike (name: string) (tx: SqliteTransaction) : Task<Result<Student list, SqliteException>> =
    queryList
      "SELECT b.id, b.name, b.age, eaddress.address\n        FROM student AS b\n        LEFT JOIN student_address AS eaddress ON b.id = eaddress.student_id\n        WHERE name LIKE \'%\' || @name || \'%\'"
      (fun cmd -> cmd.Parameters.AddWithValue("@name", name) |> ignore)
      (fun reader ->
        let hasAddress = not (reader.IsDBNull 3) in

        match hasAddress with
        | true ->
          Student.WithAddress(
            Id = reader.GetInt64 0,
            Name = reader.GetString 1,
            Age = reader.GetInt64 2,
            Address = reader.GetString 3
          )
        | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
      tx

  static member SelectByNameOrInsert
    (newItem: NewStudent)
    (tx: SqliteTransaction)
    : Task<Result<Student, SqliteException>> =
    let name =
      match newItem with
      | NewStudent.Base(name, age) -> name
      | NewStudent.WithAddress(name, age, address) -> name

    let select () =
      querySingle
        "SELECT b.id, b.name, b.age, eaddress.address FROM student b\n      LEFT JOIN student_address eaddress ON b.id = eaddress.student_id\n      WHERE name = @name LIMIT 1"
        (fun cmd -> cmd.Parameters.AddWithValue("@name", name) |> ignore)
        (fun reader ->
          let hasAddress = not (reader.IsDBNull 3) in

          match hasAddress with
          | true ->
            Student.WithAddress(
              Id = reader.GetInt64 0,
              Name = reader.GetString 1,
              Age = reader.GetInt64 2,
              Address = reader.GetString 3
            )
          | false -> Student.Base(Id = reader.GetInt64 0, Name = reader.GetString 1, Age = reader.GetInt64 2))
        tx

    querySingleOrInsert select (fun () -> Student.Insert newItem tx)


type Course with
  static member Insert (item: Course) (tx: SqliteTransaction) : Task<Result<int64, SqliteException>> =
    executeInsert
      "INSERT INTO course (code, title) VALUES (@code, @title)"
      (fun cmd ->
        cmd.Parameters.AddWithValue("@code", item.Code) |> ignore
        cmd.Parameters.AddWithValue("@title", item.Title) |> ignore)
      tx
      (fun newId -> Task.FromResult(Ok newId))

  static member SelectById (id: int64) (tx: SqliteTransaction) : Task<Result<Course option, SqliteException>> =
    querySingle
      "SELECT id, code, title FROM course WHERE id = @id"
      (fun cmd -> cmd.Parameters.AddWithValue("@id", id) |> ignore)
      (fun reader ->
        {
          Id = reader.GetInt64 0
          Code = reader.GetString 1
          Title = reader.GetString 2
        })
      tx

  static member SelectAll(tx: SqliteTransaction) : Task<Result<Course list, SqliteException>> =
    queryList
      "SELECT id, code, title FROM course"
      (fun _ -> ())
      (fun reader ->
        {
          Id = reader.GetInt64 0
          Code = reader.GetString 1
          Title = reader.GetString 2
        })
      tx

  static member Update (item: Course) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    executeWriteUnit
      "UPDATE course SET code = @code, title = @title WHERE id = @id"
      (fun cmd ->
        cmd.Parameters.AddWithValue("@id", item.Id) |> ignore
        cmd.Parameters.AddWithValue("@code", item.Code) |> ignore
        cmd.Parameters.AddWithValue("@title", item.Title) |> ignore)
      tx

  static member Delete (id: int64) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    executeWriteUnit
      "DELETE FROM course WHERE id = @id"
      (fun cmd -> cmd.Parameters.AddWithValue("@id", id) |> ignore)
      tx

  static member SelectByCode (code: string) (tx: SqliteTransaction) : Task<Result<Course list, SqliteException>> =
    queryList
      "SELECT id, code, title FROM course WHERE code = @code"
      (fun cmd -> cmd.Parameters.AddWithValue("@code", code) |> ignore)
      (fun reader ->
        {
          Id = reader.GetInt64 0
          Code = reader.GetString 1
          Title = reader.GetString 2
        })
      tx


type Enrollment with
  static member Insert (item: Enrollment) (tx: SqliteTransaction) : Task<Result<int64, SqliteException>> =
    executeInsert
      "INSERT INTO enrollment (student_id, course_id, enrolled_on) VALUES (@student_id, @course_id, @enrolled_on)"
      (fun cmd ->
        cmd.Parameters.AddWithValue("@student_id", item.StudentId) |> ignore
        cmd.Parameters.AddWithValue("@course_id", item.CourseId) |> ignore
        cmd.Parameters.AddWithValue("@enrolled_on", item.EnrolledOn) |> ignore)
      tx
      (fun newId -> Task.FromResult(Ok newId))

  static member SelectById (id: int64) (tx: SqliteTransaction) : Task<Result<Enrollment option, SqliteException>> =
    querySingle
      "SELECT id, student_id, course_id, enrolled_on FROM enrollment WHERE id = @id"
      (fun cmd -> cmd.Parameters.AddWithValue("@id", id) |> ignore)
      (fun reader ->
        {
          Id = reader.GetInt64 0
          StudentId = reader.GetInt64 1
          CourseId = reader.GetInt64 2
          EnrolledOn = reader.GetString 3
        })
      tx

  static member SelectAll(tx: SqliteTransaction) : Task<Result<Enrollment list, SqliteException>> =
    queryList
      "SELECT id, student_id, course_id, enrolled_on FROM enrollment"
      (fun _ -> ())
      (fun reader ->
        {
          Id = reader.GetInt64 0
          StudentId = reader.GetInt64 1
          CourseId = reader.GetInt64 2
          EnrolledOn = reader.GetString 3
        })
      tx

  static member Update (item: Enrollment) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    executeWriteUnit
      "UPDATE enrollment SET student_id = @student_id, course_id = @course_id, enrolled_on = @enrolled_on WHERE id = @id"
      (fun cmd ->
        cmd.Parameters.AddWithValue("@id", item.Id) |> ignore
        cmd.Parameters.AddWithValue("@student_id", item.StudentId) |> ignore
        cmd.Parameters.AddWithValue("@course_id", item.CourseId) |> ignore
        cmd.Parameters.AddWithValue("@enrolled_on", item.EnrolledOn) |> ignore)
      tx

  static member Delete (id: int64) (tx: SqliteTransaction) : Task<Result<unit, SqliteException>> =
    executeWriteUnit
      "DELETE FROM enrollment WHERE id = @id"
      (fun cmd -> cmd.Parameters.AddWithValue("@id", id) |> ignore)
      tx

  static member SelectByStudentId
    (student_id: int64)
    (tx: SqliteTransaction)
    : Task<Result<Enrollment list, SqliteException>> =
    queryList
      "SELECT id, student_id, course_id, enrolled_on FROM enrollment WHERE student_id = @student_id"
      (fun cmd -> cmd.Parameters.AddWithValue("@student_id", student_id) |> ignore)
      (fun reader ->
        {
          Id = reader.GetInt64 0
          StudentId = reader.GetInt64 1
          CourseId = reader.GetInt64 2
          EnrolledOn = reader.GetString 3
        })
      tx

  static member SelectByCourseId
    (course_id: int64)
    (tx: SqliteTransaction)
    : Task<Result<Enrollment list, SqliteException>> =
    queryList
      "SELECT id, student_id, course_id, enrolled_on FROM enrollment WHERE course_id = @course_id"
      (fun cmd -> cmd.Parameters.AddWithValue("@course_id", course_id) |> ignore)
      (fun reader ->
        {
          Id = reader.GetInt64 0
          StudentId = reader.GetInt64 1
          CourseId = reader.GetInt64 2
          EnrolledOn = reader.GetString 3
        })
      tx


type EnrollmentSummary with
  static member SelectAll(tx: SqliteTransaction) : Task<Result<EnrollmentSummary list, SqliteException>> =
    queryList
      "SELECT id, student_name, course_code FROM enrollment_summary"
      (fun _ -> ())
      (fun reader ->
        {
          Id = reader.GetInt64 0
          StudentName = reader.GetString 1
          CourseCode = reader.GetString 2
        })
      tx


type Student18 with
  static member SelectAll(tx: SqliteTransaction) : Task<Result<Student18 list, SqliteException>> =
    queryList
      "SELECT id, name, age FROM student18"
      (fun _ -> ())
      (fun reader ->
        {
          Id = reader.GetInt64 0
          Name = reader.GetString 1
          Age = reader.GetInt64 2
        })
      tx


type Student18a with
  static member SelectAll(tx: SqliteTransaction) : Task<Result<Student18a list, SqliteException>> =
    queryList
      "SELECT id, name, age FROM student18a"
      (fun _ -> ())
      (fun reader ->
        {
          Id = reader.GetInt64 0
          Name = reader.GetString 1
          Age = reader.GetInt64 2
        })
      tx
