name: Publish NuGet Package
on:
  push:
    tags:
      - '*'

jobs:                                                                        
    build:
      runs-on: ubuntu-latest
      container:
        image: mcr.microsoft.com/dotnet/sdk:8.0

      steps:
      - uses: actions/checkout@v4

      - name: check environment
        run: |
          echo $PWD
          ls
          exit 1
      
      - name: publish migtool
        run: |
          dotnet tool restore
          dotnet paket restore
          dotnet publish -c Release
          dotnet pack
          dotnet nuget push nupkg/*.nupgk -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        working-directory: ./migrate/migrate/Cli
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: publish MigrateLib
        run: |
          dotnet tool restore
          dotnet paket restore
          dotnet publish -c Release
          dotnet pack
          dotnet nuget push nupkg/*.nupgk -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        working-directory: ./migrate/migrate/Lib
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}