name: Publish NuGet Package
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0

    steps:
      - uses: actions/checkout@v4
      
      - name: publish SqliteParserCs
        run: |
          dotnet publish -c Release
          dotnet pack
          dotnet nuget push --skip-duplicate nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        working-directory: ./src/SqliteParserCs
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: publish migtool
        run: |
          dotnet publish -c Release
          dotnet pack
          dotnet nuget push --skip-duplicate nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        working-directory: ./src/mig
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      
      - name: publish MigLib
        run: |
          dotnet publish -c Release
          dotnet pack
          dotnet nuget push --skip-duplicate nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        working-directory: ./src/MigLib
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          