name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          dotnet test
